<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Sabre\\VObject' => $vendorDir . '/sabre/vobject/lib',
    'Sabre' => $vendorDir . '/sabre/dav/lib',
    'Doctrine\\DBAL\\' => $vendorDir . '/doctrine/dbal/lib',
    'Doctrine\\Common\\Lexer\\' => $vendorDir . '/doctrine/lexer/lib',
    'Doctrine\\Common\\Inflector\\' => $vendorDir . '/doctrine/inflector/lib',
    'Doctrine\\Common\\Collections\\' => $vendorDir . '/doctrine/collections/lib',
    'Doctrine\\Common\\Cache\\' => $vendorDir . '/doctrine/cache/lib',
    'Doctrine\\Common\\Annotations\\' => $vendorDir . '/doctrine/annotations/lib',
    'Doctrine\\Common\\' => $vendorDir . '/doctrine/common/lib',
);
